name = "CHERNO-SIEGE"
author = "HIDDENSNOWER"
version = "0.2.3Alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a88f43aeabfb02823f90d157a868c15885dcce263b6394d2ab83c7aa9d740d2"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"
