name = "CHERNO-SIEGE"
author = "HIDDENSNOWER"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ffc6e75a582480999a124b5474af39f4bc03b51809588519e93fb8e1b21fe95c"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"
